name: CI Python e Cobertura de Código

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  testar-e-cobrir:
    name: Testar e Enviar Cobertura
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar testes com pytest e gerar relatório de cobertura
      run: |
        pytest --cov=gerador_senha --cov-report=xml --cov-report=term-missing test_gerador_senha.py

    - name: Enviar cobertura para Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: medinapdr/tp-teste-software
      if: matrix.os == 'ubuntu-latest'